name: Deploy a Hostinger via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Subir archivos por SFTP
    runs-on: ubuntu-latest
    steps:
    - name: Obtener el código
      uses: actions/checkout@v4

    - name: Desplegar por SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local_path: './*'
        remote_path: '/home/${{ secrets.FTP_USERNAME }}/public_html/'
        sftp_only: true
        delete_remote_files: false
