name: Deploy a Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Subir archivos a Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: Obtener el código
      uses: actions/checkout@v4

    - name: Sincronizar con FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: /public_html/
        local-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/README.md
          **/.github/**
